# Generated by Django 3.2.9 on 2021-11-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
    ]
